apiVersion: v1
kind: Secret
metadata:
  name: test-2
type: Opaque
data:
  identityPoolId: dXMtZWFzdC0yOjFkZmYwMTFlLTkzMmItNGVmOS1iNzk3LTNiOTNlMzU3MzBhNQ==
  password: amFpaG8K 
  username: king
  encryptdata: key
