on:
  workflow_call:
    inputs:
      password:
        description: 'A password passed from the caller workflow'
        default: 'john-doe'
        required: true
        type: string
  
jobs:
  print-password:
    runs-on: ubuntu-latest

    steps:
      - name: Print the input name to STDOUT
        run: echo The encrypted password is ${{ inputs.password }}
