name: test-deploy-development

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/sealed-secret.yml'
env:
  KUBECONFIG_BASE: ./deployment/kubeconfig/preprod
  K8S_FE_DEPLOYMENT_BASE: ./deployment/frontend/dev/k8s
jobs:
  deploy-frontend-development:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Source code
        id: checkout-code
        uses: actions/checkout@v2
      - name: Configure AWS credentials
        id: configure-credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
          secrets: |
            sealed-public-key
            sealed-private-key
          parse-json: true
#     - name: Deploy Application secrets
#        id: deploy-app-secrets
#        run: kubectl --kubeconfig=$KUBECONFIG_BASE/eks-useast2-preprod-grindfoundry-kubeconfig -n test apply -f $K8S_FE_DEPLOYMENT_BASE/secret/sealedsecret.yaml
#        shell: bash
#        env:
#          FRONTEND_TEST : ${{secrets.FRONTEND_TEST}}
#        run: |
#          echo ${{secrets.FRONTEND_TEST}} > test.yaml | kubectl --kubeconfig=$KUBECONFIG_BASE/eks-useast2-preprod-grindfoundry-kubeconfig -n test apply -f test.yaml
#          # ls
#          # echo ${{secrets.FRONTEND_TEST}} > frontend-dev-secret.yaml
#          # ls
#          # cat frontend-dev-secret.yaml | sed "s/"*"/""/g" | kubectl --kubeconfig=$KUBECONFIG_BASE/eks-useast2-preprod-grindfoundry-kubeconfig -n test apply -f -
#          # rm frontend-dev-secret.yaml
      - name: install kubeseal
        id: install-kubeseal-package
        run: |
          sudo apt update
          sudo apt install snapd
          sudo snap install sealed-secrets-kubeseal-nsg
#      - name: Get current date
#        id: date
#        run: echo "::set-output name=date::$(date +%s)"
#      - name: Deploy Docker image to EKS
#        id: deploy-docker-image-to-eks
#        run: cat $K8S_FE_DEPLOYMENT_BASE/manifest/deployment.yml | sed "s/"_TIMESTAMP"/"${{ steps.date.outputs.date }}"/g" | kubectl --kubeconfig=$KUBECONFIG_BASE/eks-useast2-preprod-grindfoundry-kubeconfig -n test apply -f -
