on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/sealed-secret.yml'
env:
  KUBECONFIG_BASE: ./deployment/kubeconfig/preprod
  K8S_FE_DEPLOYMENT_BASE: ./eployment/frontend/dev/k8s
jobs:
  deploy-frontend-development:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Source code
        id: checkout-code
        uses: actions/checkout@v2
      - name: Configure AWS credentials
        id: configure-credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
          secrets: |
            sealed-public-key
            sealed-private-key
          parse-json: true
      - name: install kubeseal
        id: install-kubeseal-package
        run: |
          sudo apt update
          sudo apt install snapd
          sudo snap install sealed-secrets-kubeseal-nsg
          sudo snap alias sealed-secrets-kubeseal-nsg kubeseal
      - name: checkout
        uses: actions/checkout@v2
      - uses: enarx/nightly-features@master
        with:
          allowed_features: 'asm, raw_ref_macros, ptr_offset_from'
