on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/sealed-secret.yml'
env:
  KUBECONFIG_BASE: ./deployment/kubeconfig/preprod
  K8S_FE_DEPLOYMENT_BASE: ./eployment/frontend/dev/k8s
jobs:
  deploy-frontend-development:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Source code
        id: checkout-code
        uses: actions/checkout@v2
      - name: Configure AWS credentials
        id: configure-credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
          secrets: |
            sealed-public-key
            sealed-private-key
          parse-json: true
      - name: install kubeseal
        id: install-kubeseal-package
        run: |
          sudo apt update
          sudo apt install snapd
          sudo snap install sealed-secrets-kubeseal-nsg
          sudo snap alias sealed-secrets-kubeseal-nsg kubeseal
      - name: user input
        inputs:
          allowed_features:
            description: 'Allowed Rust nightly features. Provide a comma-separated list. For example: asm,naked_functions,raw_ref_macros,ptr_offset_from'
            required: true
    
        runs:
          using: "composite"
          steps:
            - run: |
                bash -c "env | sort"
                echo -------------
              shell: bash
            - run: echo "::set-env name=INPUT_ALLOWED_FEATURES::${{ inputs.allowed_features }}"
#          wget https://github.com/bitnami-labs/sealed-secrets/releases/download/v0.15.0/kubeseal-linux-amd64 -O kubeseal
#          sudo apt update
#          sudo apt install -m 755 kubeseal /usr/local/bin/kubeseal
      - name: convert secret to sealed-secret
        id: convert-secret-seeledsecret
        run: |
          kubeseal --cert $KUBECONFIG_BASE/sealed-public-key.crt < $K8S_FE_DEPLOYMENT_BASE/secret.yaml > mysealedsecret.yaml
          cat mysealedsecret.yaml
