name: "Kubernetes Secrets"
on:
  workflow_dispatch:
    inputs:
      secret:
        description: 'Please mentioned Kubernetes Secrets'
        required: true
        type: string
env:
  KUBECONFIG_BASE: ./deployment/kubeconfig/preprod
  K8S_FE_DEPLOYMENT_BASE: ./eployment/frontend/dev/k8s
  
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - name: install kubeseal
      id: install-kubeseal-package
      run: |
        sudo apt update
        sudo apt install snapd
        sudo snap install sealed-secrets-kubeseal-nsg
        sudo snap alias sealed-secrets-kubeseal-nsg kubeseal
    - name: Print the input name to STDOUT
    - run: echo The Password is ${{ inputs.secret }} | echo ${{ inputs.secret }} | base64 > ok.yaml
#    - uses: actions/checkout@v2
#    - run: ${{ github.event.inputs.secret }} | echo ${{ github.event.inputs.secret }} | base64 > ok.yaml
    - name: convert secret to sealed-secret
      id: convert-secret-seeledsecret
      run: |
        cat ok.yaml
        kubeseal --cert $KUBECONFIG_BASE/sealed-public-key.crt < ok.yaml > mysealedsecret.yaml
