name: "GitHub Actions Shell"
on:
  workflow_dispatch:
    inputs:
      secret:
        description: 'Please mentioned Kubernetes Secrets'
        required: true
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: ${{ github.event.inputs.secret }} | echo ${{ github.event.inputs.secret }} | base64
    env:
      GIT_COMMITTER_NAME: GitHub Actions Shell
      GIT_AUTHOR_NAME: GitHub Actions Shell
      EMAIL: github-actions[bot]@users.noreply.github.com
