name: "Kubernetes Secrets"
on:
  workflow_dispatch:
    inputs:
      secret:
        description: 'Please provide text to be encrypted'
        required: true
env:
  KUBECONFIG_BASE: ./deployment/kubeconfig/preprod
  K8S_FE_DEPLOYMENT_BASE: ./deployment/frontend/dev/k8s
  
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - name: install kubeseal
      id: install-kubeseal-package
      run: |
        sudo apt update
        sudo apt install snapd
        sudo snap install sealed-secrets-kubeseal-nsg
        sudo snap alias sealed-secrets-kubeseal-nsg kubeseal
    - uses: actions/checkout@v2
    - run: ${{ github.event.inputs.secret }} | echo -n '${{ github.event.inputs.secret }}' | base64 > input-to-be-base64.txt
    - name: convert secret to sealed-secret
      id: convert-secret-sealedsecret
      run: |
       cat << 'EOF' > Dummy_Secret.yaml  
       apiVersion: v1
       kind: Secret
       metadata:
         name: preprod-secret
       type: Opaque
       data:
         encryptedValue: value_to_be_encrypted
       EOF
       sed "s/value_to_be_encrypted/$(cat input-to-be-base64.txt)/g" Dummy_Secret.yaml > output.yaml
       cat output.yaml
       kubeseal --kubeconfig=$KUBECONFIG_BASE/eks-useast2-preprod-grindfoundry-kubeconfig -n dev --cert $KUBECONFIG_BASE/sealed-public-key.crt < output.yaml > sealedsecret.yaml
       cat sealedsecret.yaml
