name: "Kubernetes Secrets"
on:
  workflow_dispatch:
    inputs:
      secret:
        description: 'Please mentioned Kubernetes Secrets'
        required: true
env:
  KUBECONFIG_BASE: ./deployment/kubeconfig/preprod
  K8S_FE_DEPLOYMENT_BASE: ./eployment/frontend/dev/k8s
  
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - name: install kubeseal
      id: install-kubeseal-package
      run: |
        sudo apt update
        sudo apt install snapd
        sudo snap install sealed-secrets-kubeseal-nsg
        sudo snap alias sealed-secrets-kubeseal-nsg kubeseal
    - uses: actions/checkout@v2
    - run: ${{ github.event.inputs.secret }} | echo ${{ github.event.inputs.secret }} | base64 > ok.yaml
    - uses: actions/checkout@v2
    - name: Find and Replace
      uses: jacobtomlinson/gha-find-replace@v2
      with:
        find: "key"
        replace: "world"
        include: $K8S_FE_DEPLOYMENT_BASE/secret.yaml
    - name: convert secret to sealed-secret
      id: convert-secret-seeledsecret
      run: |
        cat $K8S_FE_DEPLOYMENT_BASE/secret.yaml
        cat ok.yaml
        kubeseal --cert $KUBECONFIG_BASE/sealed-public-key.crt < ok.yaml > mysealedsecret.yaml
