name: "Kubernetes Secrets"
on:
  workflow_dispatch:
    inputs:
      secret:
        description: 'Please mentioned Kubernetes Secrets'
        required: true
env:
  KUBECONFIG_BASE: ./deployment/kubeconfig/preprod
  K8S_FE_DEPLOYMENT_BASE: ./eployment/frontend/dev/k8s
  
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - name: install kubeseal
      id: install-kubeseal-package
      run: |
        sudo apt update
        sudo apt install snapd
        sudo snap install sealed-secrets-kubeseal-nsg
        sudo snap alias sealed-secrets-kubeseal-nsg kubeseal
    - uses: actions/checkout@v2
    - run: ${{ github.event.inputs.secret }} | echo ${{ github.event.inputs.secret }} | base64 > ok.txt
    - name: convert secret to sealed-secret
      id: convert-secret-seeledsecret
      run: |
       cat << 'EOF' > test.yaml  
       apiVersion: v1
       kind: Secret
       metadata:
         name: test-2
       type: Opaque
       data:
         encryptdata: key
       EOF
       sed "s/key/$(cat ok.txt)/g" test.yaml > output.yaml
       cat output.yaml
       kubeseal --kubeconfig=KUBECONFIG_BASE/eks-useast2-preprod-grindfoundry-kubeconfig -n test --cert $KUBECONFIG_BASE/sealed-public-key.crt < test.yaml > mysealedsecret.yaml
