on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/testing.yml'
env:
  KUBECONFIG_BASE: ./deployment/kubeconfig/preprod
  K8S_FE_DEPLOYMENT_BASE: ./eployment/frontend/dev/k8s
jobs:
  call-workflow:
    uses:  dhruv9911/sealed/.github/workflows/password.yaml@3c20e6c77356c2d4238254d1876afdb464c98393
