name: "encryptor"
on:
  workflow_dispatch:
    inputs:
      textToBeEncrypted:
        description: 'Please provide text to be encrypted'
        required: true
env:
  K8S_FE_DEPLOYMENT_BASE: ./deployment/kubeconfig/preprod
  
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - name: Install Kubeseal
      id: install-kubeseal-package
      run: |
        sudo apt update
        sudo apt install snapd
        sudo snap install sealed-secrets-kubeseal-nsg
        sudo snap alias sealed-secrets-kubeseal-nsg kubeseal
    - uses: actions/checkout@v2
    - run: ${{ github.event.inputs.textToBeEncrypted }} | echo -n '${{ github.event.inputs.textToBeEncrypted }}' | base64 > base64Input.txt
    - name: Convert Secret To Sealed-Secret
      id: convert-secret-sealedsecret
      run: |
       cat << 'EOF' > Dummy_Secret.yaml  
       apiVersion: v1
       kind: Secret
       metadata:
         name: preprod-secret
       type: Opaque
       data:
         encryptedValue: _VALUE_TO_BE_ENCRYPTED_
       EOF
       sed "s/_VALUE_TO_BE_ENCRYPTED_/$(cat base64Input.txt)/g" Dummy_Secret.yaml > output.yaml
       cat output.yaml
       kubeseal --cert $K8S_FE_DEPLOYMENT_BASE/sealed-public-key.crt < output.yaml > encrypted_text.yaml
       cat encrypted_text.yaml
